version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=memento
      - DB_USER=memento_admin
      - DB_PASS=memento_admin_pass
      - SECRET_KEY=django-insecure-ubl(46xh1j5td_tej0%x&c(pe3f

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=memento
      - POSTGRES_USER=memento_admin
      - POSTGRES_PASSWORD=memento_admin_pass
