# Generated by Django 3.2.6 on 2021-10-08 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memory_expiration',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
